version: '3'

services:
    multisfc:
        build: .
        image: multisfc
        # force start flask (not required)
        # command: /app/server.py
        network_mode: host
        hostname: multisfc
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${PWD}/repository:/app/repository
            - ${PWD}:/app:ro
        depends_on:
            - mongodb
            - memcached

    mongodb:
        image: mongo
        network_mode: host

    memcached:
        image: memcached
        network_mode: host
