domains:
  - id: domain1
    name: Domain 1
    nfvos:
      - id: tacker-site1
        name: Tacker at Domain 1
        # platform: tacker|osm
        platform: tacker
        # tacker uses auth_url, osm uses host
        auth_url: http://tacker-nfvo.local:35357/v3
        username: admin
        password: AIbxwOQKLyNhBBfJeqE9mSIE63PLrVgjJjbU3y35
        tenant-name: admin
        # a VIM name configured in this NFVO
        vim-name: VIM240
        vim-username: admin
        vim-password: AIbxwOQKLyNhBBfJeqE9mSIE63PLrVgjJjbU3y35
        # currently only "openstack" is supported
        vim-type: openstack
        # ipsec|vxlan|gre, or it can be left with no value in case of not running a multi-sfc
        tunnel: gre

  # if you don't have other domain or nfvo, just comment it
  - id: domain2
    name: Domain 2
    nfvos:
      - id: osm-site1
        name: OSM at Domain 2
        platform: osm
        # osm uses host, tacker uses auth_url
        host: osm-nfvo.local
        username: admin
        password: admin
        tenant-name: admin
        vim-name: VIM241
        vim-username: admin
        vim-password: devstack
        vim-type: openstack
        tunnel: gre
