domains:
  - id: domain1
    name: Domain 1
    nfvos:
      - id: tacker-site1
        name: Tacker at Domain 1
        # platform: tacker|osm
        platform: tacker
        host: tacker-nfvo.local
        username: admin
        password: devstack
        tenant-name: admin
        # a VIM name configured in this NFVO
        vim-name: VIM0
        vim-username: admin
        vim-password: devstack
        # currently only "openstack" is supported
        vim-type: openstack
        # ipsec|vxlan|or it can be left with no value in case of not running a multi-sfc
        tunnel: vxlan

  # if you don't have other domain or nfvo, just comment it
  - id: domain2
    name: Domain 2
    nfvos:
      - id: osm-site1
        name: OSM at Domain 2
        platform: osm
        host: osm-nfvo.local
        username: admin
        password: admin
        tenant-name: admin
        vim-name: VIM0
        vim-username: admin
        vim-password: devstack
        vim-type: openstack
        tunnel: vxlan
