domains:
  - id: domain1
    name: Domain 1
    nfvos:
      - id: tacker-site1
        name: Tacker at Domain 1
        # platform: tacker|osm
        platform: tacker
        # tacker uses auth_url, osm uses host
        auth_url: http://192.168.1.100:35357/v3
        username: user
        password: secret
        tenant-name: admin
        # a VIM name configured in this NFVO
        vim-name: VIM240
        vim-username: user
        vim-password: secret
        # currently only "openstack" is supported
        vim-type: openstack
        # ipsec|vxlan|gre, or it can be left with no value in case of not running a multi-sfc
        tunnel: gre

  # if you don't have other domain or nfvo, just comment it
  - id: domain2
    name: Domain 2
    nfvos:
      - id: osm-site1
        name: OSM at Domain 2
        platform: osm
        # osm uses host, tacker uses auth_url
        host: 192.168.1.200
        username: user
        password: secret
        tenant-name: admin
        vim-name: VIM-USSURI
        vim-username: user
        vim-password: secret
        vim-type: openstack
        tunnel: gre
