# we need to write a schema to validate this file
# commenting the following block disables federation
federation:
  protocol: saml2
  idp-name: samltest
  idp-url: https://samltest.id/idp/profile/SAML2/SOAP/ECP
  # usernames and passwords for each domain are ignored when federation is enabled
  username: rick
  password: psych

domains:
  - id: domain1
    name: Domain 1
    nfvos:
      - id: tacker-site1
        name: Tacker at Domain 1
        # platform: tacker|osm
        platform: tacker
        # tacker uses auth_url, osm uses host
        auth_url: http://tacker-nfvo.local:5000/v3
        username: admin
        password: dOBkwXa8OAJ2UrVWG8GpZVdclmDJpBbCIgxITC2p
        tenant-name: federated_project
        # a VIM name configured in this NFVO
        vim-name: VIM240
        vim-username: admin
        vim-password: dOBkwXa8OAJ2UrVWG8GpZVdclmDJpBbCIgxITC2p
        # currently only "openstack" is supported
        vim-type: openstack
        # ipsec|vxlan|gre, or it can be left with no value in case of not running a multi-sfc
        tunnel: gre

  # if you don't have other domain or nfvo, just comment it
  # - id: domain2
  #   name: Domain 2
  #   nfvos:
  #     - id: osm-site1
  #       name: OSM at Domain 2
  #       platform: osm
  #       # osm uses host, tacker uses auth_url
  #       host: osm-nfvo.local
  #       username: admin
  #       password: admin
  #       tenant-name: admin
  #       vim-name: VIM250
  #       vim-username: admin
  #       vim-password: devstack
  #       vim-type: openstack
  #       tunnel: gre
